import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/HomePage/Header'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Zanshin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header companyName='得逸信息-苏皖事业部' />
      </main>
    </div>
  )
}

export default Home
